/* VerbatimFx appearance, startup, device suggestions and recording preflight. */
(()=>{
 const $=id=>document.getElementById(id),settings=()=>window.StorageManager?.settings||{},save=()=>window.StorageManager?.saveSettings?.();
 const brands=[['fender','Fender'],['marshall','Marshall'],['vox','VOX'],['orange','Orange'],['mesa','Mesa/Boogie'],['roland','Roland'],['boss','BOSS'],['peavey','Peavey'],['line 6','Line 6'],['blackstar','Blackstar'],['yamaha','Yamaha'],['korg','Korg'],['casio','Casio'],['nord','Nord'],['steinway','Steinway'],['shure','Shure'],['sennheiser','Sennheiser'],['neumann','Neumann'],['rode','RØDE'],['akg','AKG'],['audio-technica','Audio-Technica'],['focusrite','Focusrite'],['behringer','Behringer']];
 const suggestName=label=>{const t=String(label||'').toLowerCase(),m=brands.find(([n])=>t.includes(n));if(m)return m[1];if(/mic|microphone|input/.test(t))return'Microphone';if(/piano|keyboard|keys/.test(t))return'Piano / Keyboard';if(/guitar|amp|cab/.test(t))return'Guitar Amp';if(/drum|percussion/.test(t))return'Drums / Percussion';return null;};
 async function hasPermission(h){try{if(h?.queryPermission&&await h.queryPermission({mode:'readwrite'})==='granted')return true;return!!(h?.requestPermission&&await h.requestPermission({mode:'readwrite'})==='granted');}catch{return false;}}
 async function verifyProjectAccess(){const h=window.StorageManager?.projectHandle;if(!h)return{ok:false,title:'Project folder required',detail:'Choose a project folder with full read/write access before VerbatimFx can finish starting.'};if(!(await hasPermission(h)))return{ok:false,title:'Project access required',detail:'VerbatimFx needs full read/write access to protect recordings and arrangements.'};try{const n=`.__verbatimfx_access_${Date.now()}.tmp`,f=await h.getFileHandle(n,{create:true}),w=await f.createWritable();await w.write('VerbatimFx access check');await w.close();await h.removeEntry(n);return{ok:true};}catch(e){return{ok:false,title:'Project folder is not writable',detail:`The project folder failed the write test: ${e.message}`};}}
 async function diskCheck(){if(!navigator.storage?.estimate)return{ok:true};const e=await navigator.storage.estimate();return e.quota&&e.quota-e.usage<16*1024*1024?{ok:false,title:'Storage is almost full',detail:'Free device storage before recording.'}:{ok:true};}
 async function recordingPreflight(){const bad=[await verifyProjectAccess(),await diskCheck()],audio=window.AudioManager?.activeInputs?.size||0,midi=window.AudioManager?.hasActiveMidiInputs?.();if(!audio&&!midi)bad.push({ok:false,title:'No recording input selected',detail:'Open Devices / Configuration and enable an audio or MIDI input.'});if(window.AudioManager?.audioContext?.state==='closed')bad.push({ok:false,title:'Audio engine is unavailable',detail:'Restart the audio engine from Setup or Hardware controls.'});return bad.filter(x=>!x.ok);}
 function showBlocking(m,actions=[]){let box=$('preflightDialog');if(!box){box=document.createElement('div');box.id='preflightDialog';box.className='ice-dialog-backdrop';box.innerHTML='<section class="ice-dialog ice-surface"><h2 id="preflightTitle"></h2><p id="preflightBody"></p><div id="preflightActions" class="ice-dialog-actions"></div></section>';document.body.appendChild(box);}$('preflightTitle').textContent=m.title;$('preflightBody').textContent=m.detail;const area=$('preflightActions');area.innerHTML='';actions.forEach(a=>{const b=document.createElement('button');b.className='btn '+(a.primary?'btn-primary':'');b.textContent=a.label;b.onclick=a.onclick;area.appendChild(b);});box.classList.add('open');}
 async function startupGate(){const r=await verifyProjectAccess();if(r.ok)return true;window.VerbatimFxStartup.isBlocked=true;showBlocking(r,[{label:'Choose Project Folder',primary:true,onclick:async()=>{try{const h=await window.StorageManager.selectProjectFolder();if(h&&await startupGate()){window.VerbatimFxStartup.isBlocked=false;$('preflightDialog').classList.remove('open');window.dispatchEvent(new Event('verbatimfx-project-ready'));window.dispatchEvent(new Event('verbatimfx-startup-complete'));}}catch(e){showBlocking({title:'Project selection failed',detail:e.message},[{label:'Try Again',primary:true,onclick:startupGate}]);}}}]);return false;}
 function applyAppearance(){const s=settings(),c=s.themeColor||'#7dd3fc';document.documentElement.style.setProperty('--ice-accent',c);document.documentElement.style.setProperty('--ice-accent-2',s.themeColor2||c);document.documentElement.style.setProperty('--accent',c);document.documentElement.style.setProperty('--accent-2',s.themeColor2||c);if(s.wallpaper)document.documentElement.style.setProperty('--verbatimfx-wallpaper',`url(${s.wallpaper})`);else document.documentElement.style.removeProperty('--verbatimfx-wallpaper');}
 function openSettings(){const d=$('appearanceDialog');if(!d)return;const s=settings();$('themeColor').value=s.themeColor||'#7dd3fc';$('aimEnabled').checked=!!s.aimEnabled;$('wallpaperInput').value='';d.classList.add('open');}
 function chooseWallpaper(f){if(!f)return;if(f.size>8*1024*1024){showBlocking({title:'Wallpaper is too large',detail:'Choose an image smaller than 8 MB.'},[{label:'Close',primary:true,onclick:()=>$('preflightDialog')?.classList.remove('open')}]);return;}const r=new FileReader();r.onload=()=>{settings().wallpaper=r.result;save();applyAppearance();};r.readAsDataURL(f);}
 function devicePopup(label,id){const s=suggestName(label);if(!s)return;showBlocking({title:'New equipment detected',detail:`VerbatimFx detected “${label}”. Suggested name: ${s}.`},[{label:'Use Suggested Name',primary:true,onclick:()=>{if(id&&window.StorageManager?.setAlias)window.StorageManager.setAlias(id,s);$('preflightDialog')?.classList.remove('open');window.App?.refreshHardware?.();}},{label:'Keep Name',onclick:()=>$('preflightDialog')?.classList.remove('open')}]);}
 function bind(){const help=[...document.querySelectorAll('.menu-item')].find(x=>x.textContent.includes('Help'));if(help&&!$('menuSettings')){const i=document.createElement('div');i.className='dropdown-item';i.id='menuSettings';i.textContent='Settings';help.querySelector('.dropdown').appendChild(i);i.onclick=openSettings;}$('themeColor')?.addEventListener('input',e=>{settings().themeColor=e.target.value;save();applyAppearance();});$('wallpaperInput')?.addEventListener('change',e=>chooseWallpaper(e.target.files[0]));$('clearWallpaper')?.addEventListener('click',()=>{delete settings().wallpaper;save();applyAppearance();});$('aimEnabled')?.addEventListener('change',async e=>{settings().aimEnabled=e.target.checked;save();if(e.target.checked)window.AIMHandTracking?.start?.();else window.AIMHandTracking?.stop?.();});
 let known=new Set();async function scan(){if(!navigator.mediaDevices?.enumerateDevices)return;for(const d of await navigator.mediaDevices.enumerateDevices()){if(known.size&&!known.has(d.deviceId))devicePopup(d.label,d.deviceId);known.add(d.deviceId);}}window.addEventListener('devicechange',()=>{window.App?.refreshHardware?.();scan();});window.addEventListener('midi-hardware-change',e=>devicePopup(e.detail?.name,e.detail?.id));scan();applyAppearance();if(settings().aimEnabled)window.AIMHandTracking?.start?.();
 const rec=$('masterRecord');if(rec)rec.onclick=async()=>{const bad=await recordingPreflight();if(bad.length){showBlocking(bad[0],[{label:'Open Setup',primary:true,onclick:()=>{$('preflightDialog')?.classList.remove('open');$('menuSetup')?.click();}},{label:'Try Again',onclick:()=>{$('preflightDialog')?.classList.remove('open');rec.click();}}]);return;}try{window.AudioManager.startMasterRecord();rec.classList.add('recording');rec.disabled=true;$('masterStop').disabled=false;window.App?.status?.('Recording...');}catch(e){window.App?.showError?.('Recording Error',e);}};startupGate().then(ok=>{if(ok)window.dispatchEvent(new Event('verbatimfx-startup-complete'));}}
 window.VerbatimFxStartup={startupGate,verifyProjectAccess,recordingPreflight,applyAppearance,isBlocked:false};window.VerbatimFxSuggestName=suggestName;window.addEventListener('load',bind,{once:true});
})();
